apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://dev-cluster-url
          - cluster: staging
            url: https://staging-cluster-url
          - cluster: prod
            url: https://prod-cluster-url
  template:
    metadata:
      name: "guestbook-{{cluster}}"  # tên tự động theo cluster
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: HEAD
        path: guestbook
      destination:
        server: "{{url}}"            # url tự điền từ generator
        namespace: guestbook
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
